# Generated by Django 5.1.7 on 2026-02-11 21:15

import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalog', '0003_alter_product_description_and_more'),
        ('core', '0007_remove_warehouse_uniq_warehouse_tenant_store_name_and_more'),
        ('stores', '0003_store_default_warehouse'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Purchase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('supplier_name', models.CharField(blank=True, default='', max_length=255)),
                ('invoice_number', models.CharField(blank=True, default='', max_length=64)),
                ('invoice_date', models.DateField(blank=True, null=True)),
                ('note', models.CharField(blank=True, default='', max_length=255)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('subtotal_cost', models.DecimalField(decimal_places=3, default=Decimal('0.000'), max_digits=14)),
                ('tax_amount', models.DecimalField(decimal_places=3, default=Decimal('0.000'), max_digits=14)),
                ('total_cost', models.DecimalField(decimal_places=3, default=Decimal('0.000'), max_digits=14)),
                ('status', models.CharField(choices=[('DRAFT', 'DRAFT'), ('POSTED', 'POSTED'), ('VOID', 'VOID')], default='DRAFT', max_length=16)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='purchases', to='stores.store')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.tenant')),
                ('warehouse', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.warehouse')),
            ],
        ),
        migrations.CreateModel(
            name='PurchaseLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qty', models.DecimalField(decimal_places=3, max_digits=12)),
                ('unit_cost', models.DecimalField(decimal_places=3, max_digits=12)),
                ('line_total_cost', models.DecimalField(decimal_places=3, default=Decimal('0.000'), max_digits=14)),
                ('note', models.CharField(blank=True, default='', max_length=255)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='catalog.product')),
                ('purchase', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='purchases.purchase')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.tenant')),
            ],
        ),
        migrations.AddIndex(
            model_name='purchase',
            index=models.Index(fields=['tenant', 'store', 'created_at'], name='purchases_p_tenant__5f3401_idx'),
        ),
        migrations.AddIndex(
            model_name='purchase',
            index=models.Index(fields=['tenant', 'warehouse', 'created_at'], name='purchases_p_tenant__d2a88c_idx'),
        ),
        migrations.AddIndex(
            model_name='purchase',
            index=models.Index(fields=['tenant', 'status', 'created_at'], name='purchases_p_tenant__672ee1_idx'),
        ),
        migrations.AddIndex(
            model_name='purchaseline',
            index=models.Index(fields=['tenant', 'product'], name='purchases_p_tenant__46b9f9_idx'),
        ),
        migrations.AddIndex(
            model_name='purchaseline',
            index=models.Index(fields=['tenant', 'purchase'], name='purchases_p_tenant__a1513d_idx'),
        ),
    ]
