# Generated by Django 5.1.7 on 2026-02-11 23:09

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0003_alter_product_description_and_more'),
        ('core', '0007_remove_warehouse_uniq_warehouse_tenant_store_name_and_more'),
        ('purchases', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PurchaseInvoice',
            fields=[
            ],
            options={
                'verbose_name': 'Purchase Invoice',
                'verbose_name_plural': 'Purchase Invoices',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('purchases.purchase',),
        ),
        migrations.CreateModel(
            name='Supplier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('rut', models.CharField(blank=True, max_length=32, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('phone', models.CharField(blank=True, max_length=32, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='suppliers', to='core.tenant')),
            ],
            options={
                'indexes': [models.Index(fields=['tenant', 'name'], name='purchases_s_tenant__16815e_idx')],
            },
        ),
        migrations.CreateModel(
            name='PurchaseInvoiceLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qty', models.DecimalField(decimal_places=3, max_digits=12)),
                ('unit_cost', models.DecimalField(decimal_places=3, max_digits=12)),
                ('line_total_cost', models.DecimalField(decimal_places=3, default=Decimal('0.000'), max_digits=14)),
                ('note', models.CharField(blank=True, max_length=255, null=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='catalog.product')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.tenant')),
                ('invoice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invoice_lines', to='purchases.purchaseinvoice')),
            ],
            options={
                'indexes': [models.Index(fields=['tenant', 'product'], name='purchases_p_tenant__820f5a_idx'), models.Index(fields=['tenant', 'invoice'], name='purchases_p_tenant__da1e5b_idx')],
            },
        ),
    ]
