# Generated by Django 5.1.7 on 2026-03-12 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0007_recipe_models'),
        ('core', '0008_tenant_address_tenant_city_tenant_comuna_and_more'),
        ('purchases', '0003_week2_protect_and_idempotency'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='purchaseline',
            constraint=models.CheckConstraint(condition=models.Q(('qty__gt', 0)), name='purchaseline_qty_positive'),
        ),
        migrations.AddConstraint(
            model_name='purchaseline',
            constraint=models.CheckConstraint(condition=models.Q(('unit_cost__gte', 0)), name='purchaseline_unit_cost_non_negative'),
        ),
    ]
