# Generated by Django 5.1.15 on 2026-04-01 22:53

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchases', '0004_purchaseline_qty_constraints'),
    ]

    operations = [
        migrations.AddField(
            model_name='supplier',
            name='lead_time_days',
            field=models.IntegerField(default=3, help_text='Días promedio de entrega desde que se hace el pedido'),
        ),
        migrations.AddField(
            model_name='supplier',
            name='min_order_amount',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Monto mínimo de pedido en CLP. 0 = sin mínimo', max_digits=14),
        ),
        migrations.AddField(
            model_name='supplier',
            name='min_order_qty',
            field=models.DecimalField(decimal_places=3, default=Decimal('0.000'), help_text='Cantidad mínima de pedido (MOQ). 0 = sin mínimo', max_digits=12),
        ),
        migrations.AddField(
            model_name='supplier',
            name='order_frequency_days',
            field=models.IntegerField(default=7, help_text='Frecuencia típica de pedido (cada cuántos días se pide)'),
        ),
    ]
