# Generated by Django 5.1.7 on 2026-02-27 13:09

import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalog', '0006_product_brand_product_image_url'),
        ('core', '0007_remove_warehouse_uniq_warehouse_tenant_store_name_and_more'),
        ('purchases', '0002_purchaseinvoice_supplier_purchaseinvoiceline'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ForecastModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('algorithm', models.CharField(choices=[('moving_avg', 'Media Móvil Ponderada'), ('holt_winters', 'Holt-Winters'), ('prophet', 'Prophet'), ('ensemble', 'Ensemble')], default='moving_avg', max_length=30)),
                ('version', models.IntegerField(default=1)),
                ('model_params', models.JSONField(blank=True, default=dict, help_text='Parámetros del modelo (pesos, coeficientes, etc.)')),
                ('metrics', models.JSONField(blank=True, default=dict, help_text='MAE, MAPE, RMSE del último backtest')),
                ('trained_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('data_points', models.IntegerField(default=0, help_text='Cantidad de días de datos usados')),
                ('is_active', models.BooleanField(default=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='forecast_models', to='catalog.product')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='forecast_models', to='core.tenant')),
                ('warehouse', models.ForeignKey(blank=True, help_text='null = modelo global del producto', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='forecast_models', to='core.warehouse')),
            ],
        ),
        migrations.CreateModel(
            name='Forecast',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('forecast_date', models.DateField()),
                ('qty_predicted', models.DecimalField(decimal_places=3, max_digits=12)),
                ('lower_bound', models.DecimalField(decimal_places=3, default=Decimal('0.000'), max_digits=12)),
                ('upper_bound', models.DecimalField(decimal_places=3, default=Decimal('0.000'), max_digits=12)),
                ('days_to_stockout', models.IntegerField(blank=True, null=True)),
                ('confidence', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=5)),
                ('generated_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='forecasts', to='catalog.product')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='forecasts', to='core.tenant')),
                ('warehouse', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='forecasts', to='core.warehouse')),
                ('model', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='forecasts', to='forecast.forecastmodel')),
            ],
        ),
        migrations.CreateModel(
            name='PurchaseSuggestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('supplier_name', models.CharField(blank=True, default='', max_length=255)),
                ('status', models.CharField(choices=[('PENDING', 'Pendiente'), ('APPROVED', 'Aprobada'), ('DISMISSED', 'Descartada')], default='PENDING', max_length=16)),
                ('priority', models.CharField(choices=[('CRITICAL', 'Crítico (< 3 días)'), ('HIGH', 'Alto (3-7 días)'), ('MEDIUM', 'Medio (7-14 días)'), ('LOW', 'Bajo (> 14 días)')], default='MEDIUM', max_length=16)),
                ('generated_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('total_estimated', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_suggestions', to=settings.AUTH_USER_MODEL)),
                ('purchase', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='from_suggestion', to='purchases.purchase')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='purchase_suggestions', to='core.tenant')),
                ('warehouse', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='purchase_suggestions', to='core.warehouse')),
            ],
        ),
        migrations.CreateModel(
            name='SuggestionLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('current_stock', models.DecimalField(decimal_places=3, default=Decimal('0.000'), max_digits=12)),
                ('avg_daily_demand', models.DecimalField(decimal_places=3, default=Decimal('0.000'), max_digits=12)),
                ('days_to_stockout', models.IntegerField(default=0)),
                ('suggested_qty', models.DecimalField(decimal_places=3, default=Decimal('0.000'), max_digits=12)),
                ('estimated_cost', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('reasoning', models.TextField(blank=True, default='')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='suggestion_lines', to='catalog.product')),
                ('suggestion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='forecast.purchasesuggestion')),
            ],
        ),
        migrations.CreateModel(
            name='DailySales',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('qty_sold', models.DecimalField(decimal_places=3, default=Decimal('0.000'), max_digits=12)),
                ('revenue', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14)),
                ('qty_lost', models.DecimalField(decimal_places=3, default=Decimal('0.000'), max_digits=12)),
                ('qty_received', models.DecimalField(decimal_places=3, default=Decimal('0.000'), max_digits=12)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='daily_sales', to='catalog.product')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='daily_sales', to='core.tenant')),
                ('warehouse', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='daily_sales', to='core.warehouse')),
            ],
            options={
                'indexes': [models.Index(fields=['tenant', 'product', 'date'], name='forecast_da_tenant__fcbbdd_idx'), models.Index(fields=['tenant', 'warehouse', 'date'], name='forecast_da_tenant__89d8b4_idx'), models.Index(fields=['tenant', 'date'], name='forecast_da_tenant__45d14f_idx')],
                'unique_together': {('tenant', 'product', 'warehouse', 'date')},
            },
        ),
        migrations.AddIndex(
            model_name='forecastmodel',
            index=models.Index(fields=['tenant', 'product', 'is_active'], name='forecast_fo_tenant__50b92d_idx'),
        ),
        migrations.AddIndex(
            model_name='forecastmodel',
            index=models.Index(fields=['tenant', 'product', 'warehouse', 'is_active'], name='forecast_fo_tenant__56dac5_idx'),
        ),
        migrations.AddIndex(
            model_name='forecast',
            index=models.Index(fields=['tenant', 'warehouse', 'forecast_date'], name='forecast_fo_tenant__248d98_idx'),
        ),
        migrations.AddIndex(
            model_name='forecast',
            index=models.Index(fields=['tenant', 'product', 'forecast_date'], name='forecast_fo_tenant__bb7c22_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='forecast',
            unique_together={('tenant', 'product', 'warehouse', 'forecast_date')},
        ),
        migrations.AddIndex(
            model_name='purchasesuggestion',
            index=models.Index(fields=['tenant', 'status', 'priority'], name='forecast_pu_tenant__8a34e3_idx'),
        ),
        migrations.AddIndex(
            model_name='purchasesuggestion',
            index=models.Index(fields=['tenant', 'warehouse', 'status'], name='forecast_pu_tenant__9dafae_idx'),
        ),
        migrations.AddIndex(
            model_name='suggestionline',
            index=models.Index(fields=['suggestion', 'product'], name='forecast_su_suggest_17f58b_idx'),
        ),
    ]
