# Generated by Django 5.1.7 on 2026-03-12 17:13

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0007_recipe_models'),
        ('core', '0008_tenant_address_tenant_city_tenant_comuna_and_more'),
        ('forecast', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='dailysales',
            name='gross_profit',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14),
        ),
        migrations.AddField(
            model_name='dailysales',
            name='total_cost',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14),
        ),
        migrations.AddField(
            model_name='suggestionline',
            name='margin_at_risk',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Margen bruto en riesgo por quiebre de stock', max_digits=14),
        ),
        migrations.AlterField(
            model_name='forecastmodel',
            name='algorithm',
            field=models.CharField(choices=[('simple_avg', 'Promedio Simple'), ('moving_avg', 'Media Móvil Ponderada'), ('holt_winters', 'Holt-Winters'), ('category_prior', 'Prior de Categoría'), ('prophet', 'Prophet'), ('ensemble', 'Ensemble')], default='moving_avg', max_length=30),
        ),
        migrations.CreateModel(
            name='CategoryDemandProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('avg_daily_demand', models.DecimalField(decimal_places=3, default=Decimal('0.000'), max_digits=12)),
                ('product_count', models.IntegerField(default=0, help_text='Productos con datos de venta')),
                ('data_days', models.IntegerField(default=0, help_text='Días de datos usados')),
                ('dow_factors', models.JSONField(blank=True, default=dict, help_text='Factores día-de-semana')),
                ('computed_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='demand_profiles', to='catalog.category')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='category_profiles', to='core.tenant')),
                ('warehouse', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='category_profiles', to='core.warehouse')),
            ],
            options={
                'indexes': [models.Index(fields=['tenant', 'warehouse'], name='forecast_ca_tenant__200d31_idx')],
                'unique_together': {('tenant', 'category', 'warehouse')},
            },
        ),
        migrations.CreateModel(
            name='Holiday',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('date', models.DateField()),
                ('scope', models.CharField(choices=[('NATIONAL', 'Nacional'), ('CUSTOM', 'Personalizado')], default='NATIONAL', max_length=16)),
                ('demand_multiplier', models.DecimalField(decimal_places=2, default=Decimal('1.50'), help_text='Factor de demanda en el día del feriado (1.50 = +50%)', max_digits=5)),
                ('pre_days', models.IntegerField(default=1, help_text='Días antes del feriado con demanda elevada')),
                ('pre_multiplier', models.DecimalField(decimal_places=2, default=Decimal('1.20'), help_text='Factor de demanda en días previos al feriado', max_digits=5)),
                ('is_recurring', models.BooleanField(default=True, help_text='Se repite cada año')),
                ('tenant', models.ForeignKey(blank=True, help_text='null = feriado nacional compartido', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='holidays', to='core.tenant')),
            ],
            options={
                'indexes': [models.Index(fields=['tenant', 'date'], name='forecast_ho_tenant__785651_idx'), models.Index(fields=['date'], name='forecast_ho_date_2641ba_idx')],
            },
        ),
    ]
