# Generated by Django 5.1.7 on 2026-03-12 19:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0007_recipe_models'),
        ('core', '0009_alertpreference'),
        ('forecast', '0002_add_algorithm_choices_category_profile_holiday_margins'),
    ]

    operations = [
        migrations.AddField(
            model_name='dailysales',
            name='closing_stock',
            field=models.DecimalField(blank=True, decimal_places=3, help_text='Stock al cierre del día (para detectar quiebres)', max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='dailysales',
            name='is_stockout',
            field=models.BooleanField(default=False, help_text='Probable quiebre de stock (qty_sold~0 con stock agotado)'),
        ),
        migrations.AddField(
            model_name='forecastmodel',
            name='demand_pattern',
            field=models.CharField(choices=[('smooth', 'Regular'), ('intermittent', 'Intermitente'), ('lumpy', 'Irregular'), ('insufficient', 'Datos insuficientes')], default='smooth', help_text='Patrón de demanda detectado', max_length=16),
        ),
        migrations.AddField(
            model_name='holiday',
            name='last_actual_date',
            field=models.DateField(blank=True, help_text='Última fecha en que se midió el impacto real', null=True),
        ),
        migrations.AddField(
            model_name='holiday',
            name='learned_multiplier',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Multiplicador aprendido de datos históricos', max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='forecastmodel',
            name='algorithm',
            field=models.CharField(choices=[('simple_avg', 'Promedio Simple'), ('moving_avg', 'Media Móvil Ponderada'), ('holt_winters', 'Holt-Winters'), ('category_prior', 'Prior de Categoría'), ('croston', 'Croston (Demanda Intermitente)'), ('croston_sba', 'Croston SBA'), ('ensemble', 'Ensemble')], default='moving_avg', max_length=30),
        ),
        migrations.CreateModel(
            name='ForecastAccuracy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('qty_predicted', models.DecimalField(decimal_places=3, max_digits=12)),
                ('qty_actual', models.DecimalField(decimal_places=3, max_digits=12)),
                ('error', models.DecimalField(decimal_places=3, help_text='predicted - actual', max_digits=12)),
                ('abs_pct_error', models.DecimalField(blank=True, decimal_places=2, help_text='|error| / actual × 100', max_digits=8, null=True)),
                ('algorithm', models.CharField(max_length=30)),
                ('was_stockout', models.BooleanField(default=False)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='forecast_accuracy', to='catalog.product')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='forecast_accuracy', to='core.tenant')),
                ('warehouse', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='forecast_accuracy', to='core.warehouse')),
            ],
            options={
                'indexes': [models.Index(fields=['tenant', 'date'], name='forecast_fo_tenant__0512b2_idx'), models.Index(fields=['tenant', 'algorithm', 'date'], name='forecast_fo_tenant__5fba27_idx')],
                'unique_together': {('tenant', 'product', 'warehouse', 'date')},
            },
        ),
    ]
