# Generated by Django 5.1.7 on 2026-03-16 05:22

import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0007_recipe_models'),
        ('core', '0010_warehouse_warehouse_type'),
        ('forecast', '0003_dailysales_closing_stock_dailysales_is_stockout_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SuggestionOutcome',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('suggested_qty', models.DecimalField(decimal_places=3, max_digits=12)),
                ('purchased_qty', models.DecimalField(blank=True, decimal_places=3, max_digits=12, null=True)),
                ('estimated_cost', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14)),
                ('actual_cost', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ('predicted_days', models.IntegerField(help_text='Días que se estimó duraría el stock con la qty sugerida')),
                ('actual_days_lasted', models.IntegerField(blank=True, help_text='Días reales que duró el stock después de recibir la compra', null=True)),
                ('qty_error_pct', models.DecimalField(blank=True, decimal_places=2, help_text='(purchased - suggested) / suggested × 100', max_digits=8, null=True)),
                ('days_error_pct', models.DecimalField(blank=True, decimal_places=2, help_text='(actual_days - predicted_days) / predicted_days × 100', max_digits=8, null=True)),
                ('safety_stock_adjustment', models.DecimalField(decimal_places=3, default=Decimal('0.000'), help_text='Ajuste recomendado de safety stock (+/- unidades/día)', max_digits=8)),
                ('evaluated_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('purchase_received_at', models.DateTimeField(blank=True, help_text='Cuándo se recibió la mercadería de la compra vinculada', null=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='suggestion_outcomes', to='catalog.product')),
                ('suggestion', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='outcome', to='forecast.purchasesuggestion')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='suggestion_outcomes', to='core.tenant')),
                ('warehouse', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='suggestion_outcomes', to='core.warehouse')),
            ],
            options={
                'indexes': [models.Index(fields=['tenant', 'product'], name='forecast_su_tenant__700063_idx'), models.Index(fields=['tenant', 'warehouse', 'evaluated_at'], name='forecast_su_tenant__eb1ea9_idx')],
            },
        ),
    ]
