# Generated by Django 5.1.7 on 2026-03-16 05:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forecast', '0004_add_suggestion_outcome'),
    ]

    operations = [
        migrations.AddField(
            model_name='forecastmodel',
            name='confidence_label',
            field=models.CharField(choices=[('very_high', 'Muy alta'), ('high', 'Alta'), ('medium', 'Media'), ('low', 'Baja'), ('very_low', 'Muy baja')], default='low', help_text='Etiqueta interpretable de confianza del modelo', max_length=12),
        ),
        migrations.AddField(
            model_name='forecastmodel',
            name='confidence_reason',
            field=models.CharField(blank=True, default='', help_text="Razón de la confianza (ej: '6 meses de historia, MAPE 8%')", max_length=255),
        ),
        migrations.AddField(
            model_name='forecastmodel',
            name='mape_delta',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Cambio en MAPE vs versión anterior (negativo = mejora)', max_digits=8, null=True),
        ),
        migrations.AddField(
            model_name='forecastmodel',
            name='prev_algorithm',
            field=models.CharField(blank=True, default='', help_text='Algoritmo del modelo anterior', max_length=30),
        ),
        migrations.AddField(
            model_name='forecastmodel',
            name='prev_mape',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='MAPE del modelo anterior (versión previa)', max_digits=8, null=True),
        ),
    ]
