# Generated by Django 5.1.7 on 2026-03-26 03:15

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forecast', '0005_add_confidence_label_mape_delta'),
    ]

    operations = [
        migrations.AddField(
            model_name='dailysales',
            name='promo_qty',
            field=models.DecimalField(decimal_places=3, default=Decimal('0.000'), help_text='Qty vendida bajo promoción (subconjunto de qty_sold)', max_digits=12),
        ),
        migrations.AddField(
            model_name='dailysales',
            name='promo_revenue',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Revenue de ventas promocionales (subconjunto de revenue)', max_digits=14),
        ),
    ]
