# Generated by Django 5.1.15 on 2026-04-01 22:53

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_tenant_business_type'),
        ('forecast', '0007_dailysales_forecast_only'),
    ]

    operations = [
        migrations.AddField(
            model_name='holiday',
            name='business_multipliers',
            field=models.JSONField(blank=True, default=dict, help_text='Multiplicadores por tipo de negocio. Ej: {"retail": 1.5, "restaurant": 2.0}. Si vacío, usa demand_multiplier para todos.'),
        ),
        migrations.AddField(
            model_name='holiday',
            name='duration_days',
            field=models.IntegerField(default=1, help_text='Duración del evento en días (Fiestas Patrias=3, Navidad=1)'),
        ),
        migrations.AddField(
            model_name='holiday',
            name='post_days',
            field=models.IntegerField(default=0, help_text='Días posteriores con demanda alterada (post-event dip)'),
        ),
        migrations.AddField(
            model_name='holiday',
            name='post_multiplier',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.85'), help_text='Factor post-evento (0.85 = -15% demanda tras el evento)', max_digits=5),
        ),
        migrations.AddField(
            model_name='holiday',
            name='ramp_type',
            field=models.CharField(choices=[('instant', 'Instantáneo'), ('linear', 'Gradual (rampa)'), ('plateau', 'Meseta')], default='instant', help_text='Forma de la rampa de demanda pre-evento', max_length=10),
        ),
        migrations.AlterField(
            model_name='forecastmodel',
            name='algorithm',
            field=models.CharField(choices=[('simple_avg', 'Promedio Simple'), ('moving_avg', 'Media Móvil Ponderada'), ('adaptive_ma', 'Media Móvil Adaptativa'), ('holt_winters', 'Holt-Winters'), ('hw_damped', 'Holt-Winters Amortiguado'), ('theta', 'Método Theta'), ('ets', 'ETS (Suavizamiento Exponencial)'), ('category_prior', 'Prior de Categoría'), ('croston', 'Croston (Demanda Intermitente)'), ('croston_sba', 'Croston SBA'), ('ensemble', 'Ensemble'), ('ingredient_derived', 'Derivado de Receta')], default='moving_avg', max_length=30),
        ),
        migrations.CreateModel(
            name='ForecastTrainingLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('command', models.CharField(help_text='train_forecast_models, track_accuracy, etc.', max_length=50)),
                ('status', models.CharField(choices=[('success', 'Exitoso'), ('partial', 'Parcial (con errores)'), ('failed', 'Fallido')], max_length=10)),
                ('started_at', models.DateTimeField()),
                ('finished_at', models.DateTimeField()),
                ('duration_seconds', models.FloatField(default=0)),
                ('models_trained', models.IntegerField(default=0)),
                ('models_improved', models.IntegerField(default=0)),
                ('models_kept', models.IntegerField(default=0)),
                ('models_skipped', models.IntegerField(default=0)),
                ('models_failed', models.IntegerField(default=0)),
                ('error_message', models.TextField(blank=True, default='')),
                ('error_traceback', models.TextField(blank=True, default='')),
                ('avg_mape', models.FloatField(blank=True, null=True)),
                ('algorithm_distribution', models.JSONField(blank=True, default=dict)),
                ('tenant', models.ForeignKey(blank=True, help_text='null = ejecución global (todos los tenants)', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='training_logs', to='core.tenant')),
            ],
            options={
                'ordering': ['-started_at'],
                'indexes': [models.Index(fields=['tenant', 'command', '-started_at'], name='forecast_fo_tenant__db0ef5_idx'), models.Index(fields=['status', '-started_at'], name='forecast_fo_status_03b12e_idx')],
            },
        ),
    ]
