# Generated by Django 5.1.7 on 2026-05-29 15:20

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forecast', '0008_holiday_business_multipliers_holiday_duration_days_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='dailysales',
            name='qty_sold_internal',
            field=models.DecimalField(decimal_places=3, default=Decimal('0.000'), help_text='Consumo interno (regalos/muestras): descuenta stock pero no es demanda.', max_digits=12),
        ),
    ]
