# Generated by Django 5.1.7 on 2026-08-27 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forecast', '0009_dailysales_qty_sold_internal'),
    ]

    operations = [
        migrations.AlterField(
            model_name='forecastmodel',
            name='algorithm',
            field=models.CharField(choices=[('simple_avg', 'Promedio Simple'), ('moving_avg', 'Media Móvil Ponderada'), ('adaptive_ma', 'Media Móvil Adaptativa'), ('holt_winters', 'Holt-Winters'), ('hw_damped', 'Holt-Winters Amortiguado'), ('theta', 'Método Theta'), ('ets', 'ETS (Suavizamiento Exponencial)'), ('category_prior', 'Prior de Categoría'), ('croston', 'Croston (Demanda Intermitente)'), ('croston_sba', 'Croston SBA'), ('ensemble', 'Ensemble'), ('seasonal_naive', 'Mismo dia de la semana anterior'), ('ingredient_derived', 'Derivado de Receta')], default='moving_avg', max_length=30),
        ),
    ]
