# Generated by Django 5.1.7 on 2026-09-08 18:01

import django.db.models.deletion
from django.db import migrations, models


def _mover_lo_aprendido_al_negocio(apps, schema_editor):
    """Los multiplicadores aprendidos que quedaron sobre el calendario global
    salieron de las ventas de UN negocio (auditoria del 08/09/26: 20 filas en
    produccion, todas de Marbrava, el unico con datos).

    No se borran a ciegas: si hay exactamente un negocio con ventas diarias,
    son suyos y se mueven ahi. Si hubiera mas de uno no se puede saber de cual
    vinieron, asi que se descartan -- es preferible perder el aprendizaje a
    seguir aplicandole a un cliente lo que midio otro. En los dos casos el
    calendario global queda limpio.
    """
    Holiday = apps.get_model("forecast", "Holiday")
    HolidayLearning = apps.get_model("forecast", "HolidayLearning")
    DailySales = apps.get_model("forecast", "DailySales")

    con_datos = list(DailySales.objects.values_list("tenant_id", flat=True).distinct())
    duenio = con_datos[0] if len(con_datos) == 1 else None

    aprendidos = Holiday.objects.filter(learned_multiplier__isnull=False)
    if duenio is not None:
        for h in aprendidos:
            HolidayLearning.objects.update_or_create(
                tenant_id=h.tenant_id or duenio, holiday=h,
                defaults={"learned_multiplier": h.learned_multiplier,
                          "last_actual_date": h.last_actual_date},
            )
    aprendidos.update(learned_multiplier=None, last_actual_date=None)


def _sin_vuelta(apps, schema_editor):
    """La vuelta atras deja el calendario global sin lo aprendido: es
    justamente lo que no queremos reponer."""
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0023_alter_cronheartbeat_last_result'),
        ('forecast', '0011_tsb_choice'),
    ]

    operations = [
        migrations.AlterField(
            model_name='holiday',
            name='last_actual_date',
            field=models.DateField(blank=True, help_text='OBSOLETO: usar HolidayLearning (por negocio)', null=True),
        ),
        migrations.AlterField(
            model_name='holiday',
            name='learned_multiplier',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='OBSOLETO: usar HolidayLearning (por negocio)', max_digits=5, null=True),
        ),
        migrations.CreateModel(
            name='HolidayLearning',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('learned_multiplier', models.DecimalField(decimal_places=2, help_text='Multiplicador medido con las ventas de ESTE negocio', max_digits=5)),
                ('last_actual_date', models.DateField(blank=True, help_text='Última fecha en que se midió el impacto real', null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('holiday', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='learnings', to='forecast.holiday')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='holiday_learnings', to='core.tenant')),
            ],
            options={
                'indexes': [models.Index(fields=['tenant', 'holiday'], name='forecast_ho_tenant__ff38ba_idx')],
                'unique_together': {('tenant', 'holiday')},
            },
        ),
        migrations.RunPython(_mover_lo_aprendido_al_negocio, _sin_vuelta),
    ]
