# Generated by Django 5.1.7 on 2026-03-11 03:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0008_tenant_address_tenant_city_tenant_comuna_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'Pendiente'), ('paid', 'Pagada'), ('failed', 'Fallida'), ('voided', 'Anulada')], default='pending', max_length=10)),
                ('amount_clp', models.IntegerField()),
                ('period_start', models.DateField()),
                ('period_end', models.DateField()),
                ('gateway', models.CharField(default='flow', help_text='flow | transbank | manual', max_length=40)),
                ('gateway_order_id', models.CharField(blank=True, default='', max_length=120)),
                ('gateway_tx_id', models.CharField(blank=True, default='', max_length=120)),
                ('payment_url', models.URLField(blank=True, default='', help_text='URL de pago Flow/Transbank')),
                ('paid_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Plan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(choices=[('free', 'Gratuito'), ('pro', 'Pro'), ('multi_local', 'Multi-local')], max_length=20, unique=True)),
                ('name', models.CharField(max_length=80)),
                ('price_clp', models.IntegerField(default=0, help_text='Precio mensual en CLP')),
                ('trial_days', models.IntegerField(default=14, help_text='Días de prueba gratis')),
                ('is_active', models.BooleanField(default=True)),
                ('max_products', models.IntegerField(default=100, help_text='-1 = ilimitado')),
                ('max_stores', models.IntegerField(default=1, help_text='-1 = ilimitado')),
                ('max_users', models.IntegerField(default=1, help_text='-1 = ilimitado')),
                ('has_forecast', models.BooleanField(default=False)),
                ('has_abc', models.BooleanField(default=False)),
                ('has_reports', models.BooleanField(default=False, help_text='Reportes avanzados (>3)')),
                ('has_transfers', models.BooleanField(default=False, help_text='Transferencias entre locales')),
            ],
            options={
                'ordering': ['price_clp'],
            },
        ),
        migrations.CreateModel(
            name='PaymentAttempt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('result', models.CharField(choices=[('success', 'Exitoso'), ('failed', 'Fallido'), ('pending', 'Pendiente')], default='pending', max_length=10)),
                ('gateway', models.CharField(default='flow', max_length=40)),
                ('error_msg', models.TextField(blank=True, default='')),
                ('raw', models.JSONField(default=dict, help_text='Respuesta raw de la pasarela')),
                ('attempted_at', models.DateTimeField(auto_now_add=True)),
                ('invoice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attempts', to='billing.invoice')),
            ],
            options={
                'ordering': ['-attempted_at'],
            },
        ),
        migrations.CreateModel(
            name='Subscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('trialing', 'En período de prueba'), ('active', 'Activa'), ('past_due', 'Pago pendiente'), ('suspended', 'Suspendida'), ('cancelled', 'Cancelada')], default='trialing', max_length=20)),
                ('trial_ends_at', models.DateTimeField(blank=True, null=True)),
                ('current_period_start', models.DateTimeField(blank=True, null=True)),
                ('current_period_end', models.DateTimeField(blank=True, null=True)),
                ('cancelled_at', models.DateTimeField(blank=True, null=True)),
                ('suspended_at', models.DateTimeField(blank=True, null=True)),
                ('payment_retry_count', models.IntegerField(default=0)),
                ('next_retry_at', models.DateTimeField(blank=True, null=True)),
                ('notified_7_days', models.BooleanField(default=False)),
                ('notified_3_days', models.BooleanField(default=False)),
                ('notified_1_day', models.BooleanField(default=False)),
                ('notified_past_due', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='subscriptions', to='billing.plan')),
                ('tenant', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='subscription', to='core.tenant')),
            ],
        ),
        migrations.AddField(
            model_name='invoice',
            name='subscription',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='invoices', to='billing.subscription'),
        ),
        migrations.AddIndex(
            model_name='subscription',
            index=models.Index(fields=['status'], name='billing_sub_status_948046_idx'),
        ),
        migrations.AddIndex(
            model_name='subscription',
            index=models.Index(fields=['current_period_end'], name='billing_sub_current_c59a21_idx'),
        ),
        migrations.AddIndex(
            model_name='subscription',
            index=models.Index(fields=['next_retry_at'], name='billing_sub_next_re_cde21b_idx'),
        ),
        migrations.AddIndex(
            model_name='invoice',
            index=models.Index(fields=['subscription', 'status'], name='billing_inv_subscri_4c8e1f_idx'),
        ),
    ]
