# Generated by Django 5.1.7 on 2026-03-11 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0001_initial'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='invoice',
            constraint=models.UniqueConstraint(condition=models.Q(('gateway_order_id', ''), _negated=True), fields=('gateway_order_id',), name='unique_invoice_gateway_order_id_non_empty'),
        ),
    ]
