# Generated by Django 5.1.7 on 2026-03-11 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0002_week2_protect_and_idempotency'),
        ('core', '0008_tenant_address_tenant_city_tenant_comuna_and_more'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='subscription',
            index=models.Index(fields=['status', 'current_period_end'], name='billing_sub_status_684a21_idx'),
        ),
        migrations.AddIndex(
            model_name='subscription',
            index=models.Index(fields=['status', 'next_retry_at'], name='billing_sub_status_fd932a_idx'),
        ),
    ]
