# Generated by Django 5.1.7 on 2026-03-20 02:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0003_week3_indexes'),
    ]

    operations = [
        migrations.AddField(
            model_name='plan',
            name='max_registers',
            field=models.IntegerField(default=1, help_text='Max cajas. -1 = ilimitado'),
        ),
        migrations.AlterField(
            model_name='plan',
            name='key',
            field=models.CharField(choices=[('inicio', 'Plan Inicio'), ('crecimiento', 'Plan Crecimiento'), ('pro', 'Plan Pro')], max_length=20, unique=True),
        ),
    ]
