# Generated by Django 5.1.7 on 2026-03-20 02:35

from django.db import migrations


PLANS = [
    {
        "key": "inicio",
        "name": "Plan Inicio",
        "price_clp": 19_000,
        "trial_days": 0,
        "max_products": 120,
        "max_stores": 1,
        "max_users": 10,
        "max_registers": 1,
        "has_forecast": False,
        "has_abc": False,
        "has_reports": False,
        "has_transfers": False,
        "is_active": True,
    },
    {
        "key": "crecimiento",
        "name": "Plan Crecimiento",
        "price_clp": 25_990,
        "trial_days": 0,
        "max_products": 400,
        "max_stores": 2,
        "max_users": 15,
        "max_registers": 2,
        "has_forecast": True,
        "has_abc": True,
        "has_reports": True,
        "has_transfers": False,
        "is_active": True,
    },
    {
        "key": "pro",
        "name": "Plan Pro",
        "price_clp": 59_990,
        "trial_days": 7,
        "max_products": 1000,
        "max_stores": 5,
        "max_users": -1,
        "max_registers": 5,
        "has_forecast": True,
        "has_abc": True,
        "has_reports": True,
        "has_transfers": True,
        "is_active": True,
    },
]

DEPRECATED_KEYS = ["free", "multi_local"]

# Migración de suscripciones: plan viejo → plan nuevo
PLAN_MIGRATION_MAP = {
    "free": "inicio",
    "multi_local": "pro",
    # "pro" se mantiene como "pro"
}


def forwards(apps, schema_editor):
    Plan = apps.get_model("billing", "Plan")
    Subscription = apps.get_model("billing", "Subscription")

    # 1. Crear/actualizar los 3 planes nuevos
    for plan_data in PLANS:
        key = plan_data.pop("key")
        Plan.objects.update_or_create(key=key, defaults=plan_data)
        plan_data["key"] = key

    # 2. Desactivar planes obsoletos
    Plan.objects.filter(key__in=DEPRECATED_KEYS, is_active=True).update(is_active=False)

    # 3. Migrar suscripciones de planes viejos a nuevos
    for old_key, new_key in PLAN_MIGRATION_MAP.items():
        old_plan = Plan.objects.filter(key=old_key).first()
        new_plan = Plan.objects.filter(key=new_key).first()
        if old_plan and new_plan:
            Subscription.objects.filter(plan=old_plan).update(plan=new_plan)


def backwards(apps, schema_editor):
    # No revertimos datos — seed_plans puede rehacer esto
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0004_plan_max_registers_alter_plan_key'),
    ]

    operations = [
        migrations.RunPython(forwards, backwards),
    ]
