# Generated by Django 5.1.7 on 2026-03-20 06:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0005_migrate_plans_data'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscription',
            name='card_brand',
            field=models.CharField(blank=True, default='', help_text='Marca tarjeta registrada (Visa, Mastercard)', max_length=20),
        ),
        migrations.AddField(
            model_name='subscription',
            name='card_last4',
            field=models.CharField(blank=True, default='', help_text='Últimos 4 dígitos tarjeta', max_length=4),
        ),
        migrations.AddField(
            model_name='subscription',
            name='flow_customer_id',
            field=models.CharField(blank=True, default='', help_text='ID del cliente en Flow (cus_xxx)', max_length=60),
        ),
    ]
