# Generated by Django 5.1.7 on 2026-03-24 05:37

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0006_add_flow_customer_fields'),
        ('core', '0011_add_inventory_role'),
    ]

    operations = [
        migrations.CreateModel(
            name='CheckoutSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.UUIDField(db_index=True, default=uuid.uuid4, unique=True)),
                ('email', models.EmailField(max_length=254)),
                ('status', models.CharField(choices=[('pending', 'Esperando pago'), ('paid', 'Pagado'), ('completed', 'Cuenta creada'), ('expired', 'Expirado')], default='pending', max_length=20)),
                ('amount_clp', models.IntegerField(help_text='Monto cobrado')),
                ('payment_url', models.URLField(blank=True, default='')),
                ('flow_token', models.CharField(blank=True, default='', help_text='Token de Flow para consultar estado', max_length=200)),
                ('gateway_order_id', models.CharField(blank=True, default='', max_length=120)),
                ('gateway_tx_id', models.CharField(blank=True, default='', max_length=120)),
                ('expires_at', models.DateTimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='checkout_sessions', to='billing.plan')),
                ('tenant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.tenant')),
            ],
            options={
                'indexes': [models.Index(fields=['status', 'expires_at'], name='billing_che_status_ebb9fd_idx'), models.Index(fields=['email', 'status'], name='billing_che_email_591289_idx')],
            },
        ),
    ]
