# Generated by Django 5.1.7 on 2026-04-14 06:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0007_checkoutsession'),
    ]

    operations = [
        migrations.AddField(
            model_name='checkoutsession',
            name='business_name',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
        migrations.AddField(
            model_name='checkoutsession',
            name='business_type',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AddField(
            model_name='checkoutsession',
            name='owner_name',
            field=models.CharField(blank=True, default='', max_length=150),
        ),
        migrations.AddField(
            model_name='checkoutsession',
            name='owner_password_hash',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
        migrations.AddField(
            model_name='checkoutsession',
            name='owner_username',
            field=models.CharField(blank=True, default='', max_length=150),
        ),
    ]
