# Generated by Django 5.1.7 on 2026-04-24 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0008_checkoutsession_business_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='authorization_code',
            field=models.CharField(blank=True, default='', help_text='Código de autorización del banco emisor', max_length=40),
        ),
        migrations.AddField(
            model_name='invoice',
            name='card_brand',
            field=models.CharField(blank=True, default='', help_text='Marca de tarjeta (Visa, Mastercard, Amex, etc.)', max_length=30),
        ),
        migrations.AddField(
            model_name='invoice',
            name='card_last4',
            field=models.CharField(blank=True, default='', help_text="Últimos 4 dígitos de la tarjeta (ej. '9876')", max_length=4),
        ),
        migrations.AddField(
            model_name='invoice',
            name='failure_code',
            field=models.CharField(blank=True, default='', help_text="Código de error del gateway (ej. '01')", max_length=20),
        ),
        migrations.AddField(
            model_name='invoice',
            name='failure_message',
            field=models.TextField(blank=True, default='', help_text="Mensaje de error humano (ej. 'Tarjeta vencida')"),
        ),
        migrations.AddField(
            model_name='invoice',
            name='installments',
            field=models.PositiveSmallIntegerField(blank=True, help_text='Número de cuotas si fue crédito', null=True),
        ),
        migrations.AddField(
            model_name='invoice',
            name='payment_media',
            field=models.CharField(blank=True, default='', help_text="Medio de pago Flow (ej. 'webpay', 'Mach', 'Servipag')", max_length=40),
        ),
        migrations.AddField(
            model_name='invoice',
            name='payment_media_type',
            field=models.CharField(blank=True, default='', help_text="Tipo de pago (ej. 'Crédito', 'Débito')", max_length=20),
        ),
    ]
