# Generated by Django 5.1.7 on 2026-08-24 14:37

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0010_cancel_at_period_end'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plan',
            name='key',
            field=models.CharField(help_text='Identificador interno. No se muestra al cliente.', max_length=20, unique=True, validators=[django.core.validators.RegexValidator('^[a-z][a-z0-9_]*$', 'Usa solo minusculas, numeros y guion bajo (ej: anual, pro_plus).')]),
        ),
    ]
