# Generated by Django 5.1.7 on 2026-03-11 22:21

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0008_tenant_address_tenant_city_tenant_comuna_and_more'),
        ('stores', '0003_store_default_warehouse'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CashRegister',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60)),
                ('is_active', models.BooleanField(default=True)),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cash_registers', to='stores.store')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cash_registers', to='core.tenant')),
            ],
        ),
        migrations.CreateModel(
            name='CashSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('OPEN', 'Abierta'), ('CLOSED', 'Cerrada')], default='OPEN', max_length=10)),
                ('opened_at', models.DateTimeField(auto_now_add=True)),
                ('initial_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('closed_at', models.DateTimeField(blank=True, null=True)),
                ('counted_cash', models.DecimalField(blank=True, decimal_places=2, help_text='Efectivo contado por el cajero al cierre', max_digits=12, null=True)),
                ('expected_cash', models.DecimalField(blank=True, decimal_places=2, help_text='Calculado al cierre', max_digits=12, null=True)),
                ('difference', models.DecimalField(blank=True, decimal_places=2, help_text='counted - expected', max_digits=12, null=True)),
                ('note', models.TextField(blank=True, default='')),
                ('closed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='closed_sessions', to=settings.AUTH_USER_MODEL)),
                ('opened_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='opened_sessions', to=settings.AUTH_USER_MODEL)),
                ('register', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sessions', to='caja.cashregister')),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cash_sessions', to='stores.store')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cash_sessions', to='core.tenant')),
            ],
        ),
        migrations.CreateModel(
            name='CashMovement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('IN', 'Ingreso'), ('OUT', 'Egreso')], max_length=3)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('description', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cash_movements', to=settings.AUTH_USER_MODEL)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cash_movements', to='core.tenant')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='movements', to='caja.cashsession')),
            ],
        ),
        migrations.AddIndex(
            model_name='cashregister',
            index=models.Index(fields=['tenant', 'store'], name='caja_cashre_tenant__8857a9_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='cashregister',
            unique_together={('tenant', 'store', 'name')},
        ),
        migrations.AddIndex(
            model_name='cashsession',
            index=models.Index(fields=['tenant', 'store', 'status'], name='caja_cashse_tenant__418052_idx'),
        ),
        migrations.AddConstraint(
            model_name='cashsession',
            constraint=models.UniqueConstraint(condition=models.Q(('status', 'OPEN')), fields=('tenant', 'register'), name='unique_open_session_per_register'),
        ),
        migrations.AddIndex(
            model_name='cashmovement',
            index=models.Index(fields=['tenant', 'session'], name='caja_cashmo_tenant__09f055_idx'),
        ),
    ]
