# Generated by Django 5.1.7 on 2026-04-30 00:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('caja', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cashsession',
            name='closing_snapshot',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
