# Generated by Django 5.1.7 on 2026-05-01 06:45

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('caja', '0002_closing_snapshot'),
        ('core', '0019_merge_20260426_0348'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='cashmovement',
            name='category',
            field=models.CharField(blank=True, choices=[('', 'Sin categoría'), ('SUPPLIER', 'Pago a proveedor'), ('SALARY', 'Sueldo'), ('SERVICE', 'Servicio (luz/agua/internet)'), ('OWNER_DRAW', 'Retiro del dueño'), ('REFUND', 'Devolución a cliente'), ('OTHER_OUT', 'Otro egreso'), ('CAPITAL', 'Aporte de capital'), ('EXTRA_INCOME', 'Recaudación adicional'), ('LOAN', 'Préstamo'), ('OTHER_IN', 'Otro ingreso')], default='', help_text='Categoría opcional. Permite reportes de gastos/ingresos por tipo.', max_length=20),
        ),
        migrations.AddIndex(
            model_name='cashmovement',
            index=models.Index(fields=['tenant', 'created_at'], name='caja_cashmo_tenant__430a68_idx'),
        ),
        migrations.AddIndex(
            model_name='cashmovement',
            index=models.Index(fields=['tenant', 'type', 'category'], name='caja_cashmo_tenant__53d2cf_idx'),
        ),
    ]
