# Generated by Django 5.1.7 on 2026-05-01 20:16

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


# Plantilla de categorías default — se crea para cada tenant.
# Match exacto con el enum CharField anterior para que el backfill
# pueda linkear movimientos viejos por `code`.
DEFAULT_CATEGORIES = [
    # Egresos
    ("SUPPLIER",     "Pago a proveedor",                "OUT",   1),
    ("SALARY",       "Sueldo",                          "OUT",   2),
    ("SERVICE",      "Servicio (luz/agua/internet)",    "OUT",   3),
    ("OWNER_DRAW",   "Retiro del dueño",                "OUT",   4),
    ("REFUND",       "Devolución a cliente",            "OUT",   5),
    ("OTHER_OUT",    "Otro egreso",                     "OUT",   6),
    # Ingresos
    ("CAPITAL",      "Aporte de capital",               "IN",    1),
    ("EXTRA_INCOME", "Recaudación adicional",           "IN",    2),
    ("LOAN",         "Préstamo",                        "IN",    3),
    ("OTHER_IN",     "Otro ingreso",                    "IN",    4),
]


def seed_default_categories_and_link(apps, schema_editor):
    """
    Para cada Tenant existente:
    1. Crear las 10 categorías default como MovementCategory.
    2. Linkear cada CashMovement.category (string) → category_fk (FK).

    Idempotente: si ya hay categorías, las omite (re-run safe).
    Si CashMovement.category está vacío, queda category_fk=NULL.
    """
    Tenant = apps.get_model("core", "Tenant")
    MovementCategory = apps.get_model("caja", "MovementCategory")
    CashMovement = apps.get_model("caja", "CashMovement")

    for tenant in Tenant.objects.all():
        # 1. Crear categorías default
        existing_codes = set(
            MovementCategory.objects.filter(tenant=tenant).values_list("code", flat=True)
        )
        new_cats = []
        for code, label, type_, order in DEFAULT_CATEGORIES:
            if code in existing_codes:
                continue
            new_cats.append(MovementCategory(
                tenant=tenant, code=code, label=label, type=type_,
                is_default_template=True, is_active=True, order=order,
            ))
        if new_cats:
            MovementCategory.objects.bulk_create(new_cats)

        # 2. Linkear movimientos existentes
        # Map code → MovementCategory para este tenant
        cat_map = {
            mc.code: mc.id
            for mc in MovementCategory.objects.filter(tenant=tenant)
        }
        # Por cada CashMovement con category != "" sin FK, setear FK
        movs_to_update = CashMovement.objects.filter(
            tenant=tenant,
            category_fk__isnull=True,
        ).exclude(category="")
        # Bulk update por código (más eficiente que loop)
        for code, cat_id in cat_map.items():
            movs_to_update.filter(category=code).update(category_fk_id=cat_id)


def reverse_seed(apps, schema_editor):
    """Limpiar default templates (no afecta movimientos — usan SET_NULL)."""
    MovementCategory = apps.get_model("caja", "MovementCategory")
    MovementCategory.objects.filter(is_default_template=True).delete()


class Migration(migrations.Migration):

    dependencies = [
        ('caja', '0003_add_movement_category'),
        ('core', '0019_merge_20260426_0348'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cashmovement',
            name='category',
            field=models.CharField(blank=True, choices=[('', 'Sin categoría'), ('SUPPLIER', 'Pago a proveedor'), ('SALARY', 'Sueldo'), ('SERVICE', 'Servicio (luz/agua/internet)'), ('OWNER_DRAW', 'Retiro del dueño'), ('REFUND', 'Devolución a cliente'), ('OTHER_OUT', 'Otro egreso'), ('CAPITAL', 'Aporte de capital'), ('EXTRA_INCOME', 'Recaudación adicional'), ('LOAN', 'Préstamo'), ('OTHER_IN', 'Otro ingreso')], default='', help_text='DEPRECATED: usar category_fk. Mantenido por compat.', max_length=40),
        ),
        migrations.CreateModel(
            name='MovementCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.SlugField(help_text='Identificador interno (auto-generado del label si está vacío)', max_length=40)),
                ('label', models.CharField(max_length=80)),
                ('type', models.CharField(choices=[('IN', 'Ingreso'), ('OUT', 'Egreso'), ('BOTH', 'Ambos')], default='OUT', max_length=4)),
                ('icon', models.CharField(blank=True, default='', help_text='Emoji opcional (🛒 💰 etc.)', max_length=8)),
                ('color', models.CharField(blank=True, default='', help_text='Color hex opcional (#FF0000 o #FF0000FF)', max_length=9)),
                ('is_default_template', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('order', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='movement_categories', to='core.tenant')),
            ],
            options={
                'ordering': ['type', 'order', 'label'],
            },
        ),
        migrations.AddField(
            model_name='cashmovement',
            name='category_fk',
            field=models.ForeignKey(blank=True, help_text='Categoría personalizable del tenant (FK a MovementCategory).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='movements', to='caja.movementcategory'),
        ),
        migrations.AddIndex(
            model_name='movementcategory',
            index=models.Index(fields=['tenant', 'is_active'], name='caja_moveme_tenant__b53c3b_idx'),
        ),
        migrations.AddIndex(
            model_name='movementcategory',
            index=models.Index(fields=['tenant', 'type'], name='caja_moveme_tenant__4ed76b_idx'),
        ),
        migrations.AddConstraint(
            model_name='movementcategory',
            constraint=models.UniqueConstraint(fields=('tenant', 'code'), name='unique_movement_category_code_per_tenant'),
        ),
        # Backfill: crear categorías default + linkear movimientos viejos
        migrations.RunPython(seed_default_categories_and_link, reverse_seed),
    ]
