# Generated by Django 5.1.7 on 2026-02-18 20:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0004_category_is_active_category_parent_product_cost_and_more'),
        ('core', '0007_remove_warehouse_uniq_warehouse_tenant_store_name_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Unit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=20)),
                ('name', models.CharField(max_length=60)),
                ('is_base', models.BooleanField(default=False)),
                ('conversion_factor', models.DecimalField(decimal_places=8, default=1, help_text='1 esta unidad = X unidades base (ej: 1 KG = 1000 GR → factor=1000)', max_digits=18)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.AddField(
            model_name='barcode',
            name='barcode_type',
            field=models.CharField(blank=True, choices=[('EAN13', 'EAN-13'), ('EAN8', 'EAN-8'), ('CODE128', 'Code 128'), ('QR', 'QR Code'), ('INTERNAL', 'Código Interno')], default='EAN13', max_length=20),
        ),
        migrations.AddIndex(
            model_name='barcode',
            index=models.Index(fields=['tenant', 'product'], name='catalog_bar_tenant__8419ab_idx'),
        ),
        migrations.AddField(
            model_name='unit',
            name='base_unit',
            field=models.ForeignKey(blank=True, help_text='Unidad base para conversión (ej: GR -> KG)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='derived_units', to='catalog.unit'),
        ),
        migrations.AddField(
            model_name='unit',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='units', to='core.tenant'),
        ),
        migrations.AddField(
            model_name='product',
            name='unit_obj',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='products', to='catalog.unit'),
        ),
        migrations.AddIndex(
            model_name='unit',
            index=models.Index(fields=['tenant', 'code'], name='catalog_uni_tenant__bdc349_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='unit',
            unique_together={('tenant', 'code')},
        ),
    ]
