# Generated by Django 5.1.7 on 2026-03-11 22:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0006_product_brand_product_image_url'),
        ('core', '0008_tenant_address_tenant_city_tenant_comuna_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Recipe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True)),
                ('notes', models.CharField(blank=True, default='', max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('product', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='recipe', to='catalog.product')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='recipes', to='core.tenant')),
            ],
        ),
        migrations.CreateModel(
            name='RecipeLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qty', models.DecimalField(decimal_places=4, help_text='Cantidad de ingrediente por 1 unidad del producto padre', max_digits=12)),
                ('ingredient', models.ForeignKey(help_text='Producto/ingrediente a descontar del stock', on_delete=django.db.models.deletion.PROTECT, related_name='used_in_recipes', to='catalog.product')),
                ('recipe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='catalog.recipe')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='recipe_lines', to='core.tenant')),
            ],
        ),
        migrations.AddIndex(
            model_name='recipe',
            index=models.Index(fields=['tenant', 'product'], name='catalog_rec_tenant__9cbedc_idx'),
        ),
        migrations.AddIndex(
            model_name='recipe',
            index=models.Index(fields=['tenant', 'is_active'], name='catalog_rec_tenant__9f895b_idx'),
        ),
        migrations.AddIndex(
            model_name='recipeline',
            index=models.Index(fields=['tenant', 'recipe'], name='catalog_rec_tenant__59269d_idx'),
        ),
        migrations.AddIndex(
            model_name='recipeline',
            index=models.Index(fields=['tenant', 'ingredient'], name='catalog_rec_tenant__e8817d_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='recipeline',
            unique_together={('recipe', 'ingredient')},
        ),
    ]
