# Generated by Django 5.1.7 on 2026-03-16 06:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0007_recipe_models'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipeline',
            name='unit',
            field=models.ForeignKey(blank=True, help_text='Unidad de la cantidad. Si null, se usa la unidad del ingrediente.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='recipe_lines', to='catalog.unit'),
        ),
        migrations.AddField(
            model_name='unit',
            name='family',
            field=models.CharField(choices=[('MASS', 'Masa'), ('VOLUME', 'Volumen'), ('LENGTH', 'Longitud'), ('COUNT', 'Conteo')], default='COUNT', max_length=10),
        ),
    ]
