# Generated by Django 5.1.7 on 2026-05-06 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0012_product_allow_negative_stock'),
        ('core', '0019_merge_20260426_0348'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='deleted_at',
            field=models.DateTimeField(blank=True, db_index=True, help_text='Si tiene fecha, el producto está borrado lógicamente. No aparece en catálogo/POS pero sí en reportes históricos.', null=True),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['tenant', 'deleted_at'], name='catalog_pro_tenant__b3d52d_idx'),
        ),
    ]
