# Generated by Django 5.1.7 on 2026-05-06 14:27

import django.db.models.manager
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0013_add_product_deleted_at'),
        ('core', '0019_merge_20260426_0348'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'base_manager_name': 'all_objects'},
        ),
        migrations.AlterModelManagers(
            name='product',
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('all_objects', django.db.models.manager.Manager()),
            ],
        ),
        migrations.RemoveConstraint(
            model_name='product',
            name='uniq_product_sku_per_tenant_nonempty',
        ),
        migrations.AddConstraint(
            model_name='product',
            constraint=models.UniqueConstraint(condition=models.Q(models.Q(('sku', ''), _negated=True), ('deleted_at__isnull', True)), fields=('tenant', 'sku'), name='uniq_product_sku_per_tenant_nonempty'),
        ),
    ]
