# Generated by Django 5.1.7 on 2026-05-29 04:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0014_update_sku_unique_for_deleted'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='is_combo',
            field=models.BooleanField(default=False, help_text='Si está activo, este producto es un combo/pack de otros productos a precio fijo.'),
        ),
    ]
