# Generated by Django 5.1.7 on 2026-03-12 00:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalog', '0007_recipe_models'),
        ('core', '0008_tenant_address_tenant_city_tenant_comuna_and_more'),
        ('sales', '0011_add_cash_session'),
        ('stores', '0003_store_default_warehouse'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Table',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60)),
                ('capacity', models.PositiveSmallIntegerField(default=4)),
                ('status', models.CharField(choices=[('FREE', 'Libre'), ('OPEN', 'Ocupada')], default='FREE', max_length=8)),
                ('is_active', models.BooleanField(default=True)),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='tables', to='stores.store')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='tables', to='core.tenant')),
            ],
        ),
        migrations.CreateModel(
            name='OpenOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('OPEN', 'Abierta'), ('CLOSED', 'Cerrada')], default='OPEN', max_length=8)),
                ('opened_at', models.DateTimeField(auto_now_add=True)),
                ('closed_at', models.DateTimeField(blank=True, null=True)),
                ('note', models.CharField(blank=True, default='', max_length=255)),
                ('opened_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='opened_orders', to=settings.AUTH_USER_MODEL)),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='open_orders', to='stores.store')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='open_orders', to='core.tenant')),
                ('warehouse', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='open_orders', to='core.warehouse')),
                ('table', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='orders', to='tables.table')),
            ],
        ),
        migrations.CreateModel(
            name='OpenOrderLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qty', models.DecimalField(decimal_places=3, max_digits=12)),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=12)),
                ('note', models.CharField(blank=True, default='', max_length=255)),
                ('added_at', models.DateTimeField(auto_now_add=True)),
                ('is_paid', models.BooleanField(default=False)),
                ('added_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='added_order_lines', to=settings.AUTH_USER_MODEL)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='tables.openorder')),
                ('paid_by_sale', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='paid_order_lines', to='sales.sale')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='order_lines', to='catalog.product')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='order_lines', to='core.tenant')),
            ],
            options={
                'indexes': [models.Index(fields=['tenant', 'order'], name='tables_open_tenant__a93353_idx'), models.Index(fields=['tenant', 'order', 'is_paid'], name='tables_open_tenant__8f17ce_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='table',
            index=models.Index(fields=['tenant', 'store', 'status'], name='tables_tabl_tenant__51d118_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='table',
            unique_together={('tenant', 'store', 'name')},
        ),
        migrations.AddIndex(
            model_name='openorder',
            index=models.Index(fields=['tenant', 'store', 'status'], name='tables_open_tenant__d8de23_idx'),
        ),
        migrations.AddIndex(
            model_name='openorder',
            index=models.Index(fields=['tenant', 'table', 'status'], name='tables_open_tenant__a9b61d_idx'),
        ),
        migrations.AddConstraint(
            model_name='openorder',
            constraint=models.UniqueConstraint(condition=models.Q(('status', 'OPEN')), fields=('tenant', 'table'), name='unique_open_order_per_table'),
        ),
    ]
