# Generated by Django 5.1.7 on 2026-03-12 01:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tables', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='table',
            name='is_counter',
            field=models.BooleanField(default=False, help_text='True para posiciones de mostrador/para llevar'),
        ),
        migrations.AddField(
            model_name='table',
            name='zone',
            field=models.CharField(blank=True, default='', help_text='Zona del local: Salón Grande, Ventanas, etc.', max_length=60),
        ),
    ]
