# Generated by Django 5.1.7 on 2026-03-12 04:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tables', '0002_table_is_counter_table_zone'),
    ]

    operations = [
        migrations.AddField(
            model_name='openorder',
            name='customer_name',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
    ]
