# Generated by Django 5.1.7 on 2026-03-12 04:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tables', '0003_add_customer_name_to_openorder'),
    ]

    operations = [
        migrations.AddField(
            model_name='openorderline',
            name='cancelled_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='openorderline',
            name='is_cancelled',
            field=models.BooleanField(default=False),
        ),
    ]
