# Generated by Django 5.1.7 on 2026-04-03 05:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tables', '0004_add_is_cancelled_to_orderline'),
    ]

    operations = [
        migrations.AddField(
            model_name='openorderline',
            name='cancel_reason',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
    ]
