# Generated by Django 5.1.7 on 2026-04-06 04:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tables', '0005_openorderline_cancel_reason'),
    ]

    operations = [
        migrations.AddField(
            model_name='table',
            name='height',
            field=models.FloatField(default=8, help_text='Height in floor plan units'),
        ),
        migrations.AddField(
            model_name='table',
            name='position_x',
            field=models.FloatField(default=0, help_text='X position in floor plan (0-100)'),
        ),
        migrations.AddField(
            model_name='table',
            name='position_y',
            field=models.FloatField(default=0, help_text='Y position in floor plan (0-100)'),
        ),
        migrations.AddField(
            model_name='table',
            name='rotation',
            field=models.FloatField(default=0, help_text='Rotation in degrees (0-360)'),
        ),
        migrations.AddField(
            model_name='table',
            name='shape',
            field=models.CharField(choices=[('round', 'Redonda'), ('square', 'Cuadrada'), ('rect', 'Rectangular')], default='square', max_length=10),
        ),
        migrations.AddField(
            model_name='table',
            name='width',
            field=models.FloatField(default=8, help_text='Width in floor plan units'),
        ),
    ]
