# Generated by Django 5.1.7 on 2026-05-17 07:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tables', '0007_orderline_add_lines_batch_key'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='openorder',
            name='waiter',
            field=models.ForeignKey(blank=True, help_text='Garzon/mozo que atiende la mesa (Fudo-style)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders_attended', to=settings.AUTH_USER_MODEL),
        ),
    ]
