# Generated by Django 5.1.7 on 2026-02-05 19:00

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0003_alter_product_description_and_more'),
        ('core', '0007_remove_warehouse_uniq_warehouse_tenant_store_name_and_more'),
        ('inventory', '0003_alter_stockitem_product_alter_stockitem_warehouse_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='stockmove',
            name='reason',
            field=models.CharField(blank=True, default='', max_length=32),
        ),
        migrations.AddIndex(
            model_name='stockitem',
            index=models.Index(fields=['tenant', 'warehouse'], name='inventory_s_tenant__f351c1_idx'),
        ),
        migrations.AddIndex(
            model_name='stockitem',
            index=models.Index(fields=['tenant', 'product'], name='inventory_s_tenant__76e818_idx'),
        ),
        migrations.AddIndex(
            model_name='stockmove',
            index=models.Index(fields=['tenant', 'warehouse', 'created_at'], name='inventory_s_tenant__5aa90f_idx'),
        ),
        migrations.AddConstraint(
            model_name='stockitem',
            constraint=models.CheckConstraint(condition=models.Q(('on_hand__gte', 0)), name='stockitem_on_hand_gte_0'),
        ),
    ]
