# Generated by Django 5.1.7 on 2026-02-11 20:40

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0005_stocktransfer_stocktransferline_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='stockitem',
            name='avg_cost',
            field=models.DecimalField(decimal_places=3, default=Decimal('0.000'), max_digits=12),
        ),
        migrations.AddField(
            model_name='stockitem',
            name='stock_value',
            field=models.DecimalField(decimal_places=3, default=Decimal('0.000'), max_digits=14),
        ),
        migrations.AddField(
            model_name='stockmove',
            name='cost_snapshot',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='stockmove',
            name='value_delta',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=14, null=True),
        ),
    ]
