# Generated by Django 5.1.7 on 2026-03-11 17:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_tenant_address_tenant_city_tenant_comuna_and_more'),
        ('inventory', '0006_stockitem_avg_cost_stockitem_stock_value_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stockitem',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.tenant'),
        ),
        migrations.AlterField(
            model_name='stockmove',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.tenant'),
        ),
        migrations.AlterField(
            model_name='stocktransfer',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.tenant'),
        ),
        migrations.AlterField(
            model_name='stocktransferline',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.tenant'),
        ),
    ]
