# Generated by Django 5.1.7 on 2026-08-24 00:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0007_week2_protect_and_idempotency'),
    ]

    operations = [
        migrations.AddField(
            model_name='stockitem',
            name='min_stock_auto',
            field=models.DecimalField(blank=True, decimal_places=3, help_text='Minimo sugerido por el sistema. Null = sin consumo reciente.', max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='stockitem',
            name='min_stock_auto_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
