# Generated by Django 5.1.7 on 2026-01-29 06:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0002_tenant_default_warehouse'),
    ]

    operations = [
        migrations.CreateModel(
            name='Store',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('code', models.CharField(blank=True, default='', max_length=40)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='stores', to='core.tenant')),
            ],
            options={
                'indexes': [models.Index(fields=['tenant', 'name'], name='stores_stor_tenant__570ed0_idx')],
                'unique_together': {('tenant', 'name')},
            },
        ),
    ]
