# Generated by Django 5.1.7 on 2026-01-29 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_remove_warehouse_core_wareho_tenant__2a4679_idx_and_more'),
        ('stores', '0001_initial'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='store',
            index=models.Index(fields=['tenant', 'is_active'], name='stores_stor_tenant__faf833_idx'),
        ),
    ]
