# Generated by Django 5.1.7 on 2026-01-31 19:26

import django.db.models.deletion
from django.db import migrations, models


def forwards(apps, schema_editor):
    Store = apps.get_model("stores", "Store")
    Warehouse = apps.get_model("core", "Warehouse")

    # Para cada Store existente:
    # - si ya tiene default_warehouse, no tocar
    # - si no tiene, asignar la primera Warehouse activa del mismo tenant+store
    for s in Store.objects.all().iterator():
        if getattr(s, "default_warehouse_id", None):
            continue

        wh = (
            Warehouse.objects.filter(
                tenant_id=s.tenant_id,
                store_id=s.id,
                is_active=True,
            )
            .order_by("id")
            .first()
        )

        if wh:
            s.default_warehouse_id = wh.id
            s.save(update_fields=["default_warehouse"])


def backwards(apps, schema_editor):
    Store = apps.get_model("stores", "Store")
    Store.objects.update(default_warehouse=None)


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0007_remove_warehouse_uniq_warehouse_tenant_store_name_and_more"),
        ("stores", "0002_store_stores_stor_tenant__faf833_idx"),
    ]

    operations = [
        migrations.AddField(
            model_name="store",
            name="default_warehouse",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="default_for_stores",
                to="core.warehouse",
            ),
        ),
        migrations.RunPython(forwards, backwards),
    ]
