# Generated by Django 5.1.7 on 2026-01-29 06:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_tenant_default_warehouse'),
        ('stores', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='warehouse',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='user',
            name='active_store',
            field=models.ForeignKey(blank=True, help_text='Local activo seleccionado por el usuario', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='active_users', to='stores.store'),
        ),
        migrations.AddField(
            model_name='warehouse',
            name='store',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='warehouses', to='stores.store'),
        ),
        migrations.AlterUniqueTogether(
            name='warehouse',
            unique_together={('tenant', 'store', 'name')},
        ),
        migrations.AddIndex(
            model_name='warehouse',
            index=models.Index(fields=['tenant', 'store', 'name'], name='core_wareho_tenant__a20b50_idx'),
        ),
    ]
