# Generated by Django 5.1.7 on 2026-01-29 06:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_warehouse_unique_together_user_active_store_and_more'),
        ('stores', '0001_initial'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='warehouse',
            name='core_wareho_tenant__a20b50_idx',
        ),
        migrations.AlterUniqueTogether(
            name='warehouse',
            unique_together={('tenant', 'name')},
        ),
        migrations.AlterField(
            model_name='user',
            name='active_store',
            field=models.ForeignKey(blank=True, help_text='Local activo por defecto del usuario', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='active_users', to='stores.store'),
        ),
        migrations.RemoveField(
            model_name='warehouse',
            name='store',
        ),
    ]
