# Generated by Django 5.1.7 on 2026-01-29 17:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_remove_warehouse_core_wareho_tenant__a20b50_idx_and_more'),
        ('stores', '0001_initial'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='warehouse',
            name='core_wareho_tenant__2a4679_idx',
        ),
        migrations.AlterUniqueTogether(
            name='warehouse',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='warehouse',
            name='store',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='warehouses', to='stores.store'),
        ),
        migrations.AlterField(
            model_name='user',
            name='active_store',
            field=models.ForeignKey(blank=True, help_text='Local activo del usuario dentro del tenant', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='stores.store'),
        ),
        migrations.AlterUniqueTogether(
            name='warehouse',
            unique_together={('tenant', 'store', 'name')},
        ),
        migrations.AddIndex(
            model_name='warehouse',
            index=models.Index(fields=['tenant', 'store', 'name'], name='core_wareho_tenant__a20b50_idx'),
        ),
        migrations.AddIndex(
            model_name='warehouse',
            index=models.Index(fields=['tenant', 'store', 'is_active'], name='core_wareho_tenant__6d539c_idx'),
        ),
    ]
