# Generated by Django 5.1.7 on 2026-01-29 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_remove_warehouse_core_wareho_tenant__2a4679_idx_and_more'),
        ('stores', '0002_store_stores_stor_tenant__faf833_idx'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='warehouse',
            unique_together=set(),
        ),
        migrations.AddConstraint(
            model_name='warehouse',
            constraint=models.UniqueConstraint(fields=('tenant', 'store', 'name'), name='uniq_warehouse_tenant_store_name'),
        ),
    ]
