# Generated by Django 5.1.7 on 2026-01-31 19:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_alter_warehouse_unique_together_and_more'),
        ('stores', '0002_store_stores_stor_tenant__faf833_idx'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='warehouse',
            name='uniq_warehouse_tenant_store_name',
        ),
        migrations.AlterField(
            model_name='warehouse',
            name='store',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='warehouses', to='stores.store'),
        ),
        migrations.AlterUniqueTogether(
            name='warehouse',
            unique_together={('tenant', 'store', 'name')},
        ),
    ]
