# Generated by Django 5.1.7 on 2026-03-04 05:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_remove_warehouse_uniq_warehouse_tenant_store_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tenant',
            name='address',
            field=models.CharField(blank=True, default='', max_length=300),
        ),
        migrations.AddField(
            model_name='tenant',
            name='city',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='tenant',
            name='comuna',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='tenant',
            name='currency',
            field=models.CharField(default='CLP', max_length=3),
        ),
        migrations.AddField(
            model_name='tenant',
            name='email',
            field=models.EmailField(blank=True, default='', max_length=254),
        ),
        migrations.AddField(
            model_name='tenant',
            name='giro',
            field=models.CharField(blank=True, default='', help_text='Giro comercial', max_length=200),
        ),
        migrations.AddField(
            model_name='tenant',
            name='legal_name',
            field=models.CharField(blank=True, default='', help_text='Razón social', max_length=200),
        ),
        migrations.AddField(
            model_name='tenant',
            name='logo_url',
            field=models.URLField(blank=True, default='', help_text='URL del logo de la empresa'),
        ),
        migrations.AddField(
            model_name='tenant',
            name='phone',
            field=models.CharField(blank=True, default='', max_length=30),
        ),
        migrations.AddField(
            model_name='tenant',
            name='primary_color',
            field=models.CharField(blank=True, default='#4F46E5', help_text='Color principal (hex)', max_length=7),
        ),
        migrations.AddField(
            model_name='tenant',
            name='receipt_footer',
            field=models.TextField(blank=True, default='', help_text='Texto al pie de boletas (ej: políticas de devolución)'),
        ),
        migrations.AddField(
            model_name='tenant',
            name='receipt_header',
            field=models.TextField(blank=True, default='', help_text='Texto adicional en el encabezado de boletas'),
        ),
        migrations.AddField(
            model_name='tenant',
            name='receipt_show_logo',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='tenant',
            name='receipt_show_rut',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='tenant',
            name='rut',
            field=models.CharField(blank=True, default='', help_text='RUT empresa (ej: 76.123.456-7)', max_length=15),
        ),
        migrations.AddField(
            model_name='tenant',
            name='tax_rate',
            field=models.DecimalField(decimal_places=2, default=19, help_text='IVA por defecto (%)', max_digits=5),
        ),
        migrations.AddField(
            model_name='tenant',
            name='timezone',
            field=models.CharField(default='America/Santiago', max_length=50),
        ),
        migrations.AddField(
            model_name='tenant',
            name='website',
            field=models.URLField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('owner', 'Dueño'), ('manager', 'Administrador'), ('cashier', 'Cajero')], default='owner', help_text='Rol del usuario en el tenant', max_length=10),
        ),
    ]
