# Generated by Django 5.1.7 on 2026-03-12 18:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_tenant_address_tenant_city_tenant_comuna_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AlertPreference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stock_bajo', models.BooleanField(default=True)),
                ('forecast_urgente', models.BooleanField(default=True)),
                ('sugerencia_compra', models.BooleanField(default=True)),
                ('merma_alta', models.BooleanField(default=False)),
                ('sin_rotacion', models.BooleanField(default=False)),
                ('resumen_diario', models.BooleanField(default=False)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='alert_prefs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'core_alertpreference',
            },
        ),
    ]
