# Generated by Django 5.1.7 on 2026-03-13 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_alertpreference'),
    ]

    operations = [
        migrations.AddField(
            model_name='warehouse',
            name='warehouse_type',
            field=models.CharField(choices=[('sales_floor', 'Sala de venta'), ('storage', 'Bodega')], default='storage', help_text='Tipo: sala de venta o bodega de almacenamiento', max_length=16),
        ),
    ]
