# Generated by Django 5.1.7 on 2026-03-20 02:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_warehouse_warehouse_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('owner', 'Dueño/Gerente'), ('manager', 'Administrador'), ('cashier', 'Caja y/o Garzón'), ('inventory', 'Inventario')], default='owner', help_text='Rol del usuario en el tenant', max_length=10),
        ),
    ]
