# Generated by Django 5.1.15 on 2026-04-01 22:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_add_inventory_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='tenant',
            name='business_type',
            field=models.CharField(choices=[('retail', 'Minimarket / Retail'), ('restaurant', 'Restaurant / Cafetería'), ('hardware', 'Ferretería / Materiales'), ('wholesale', 'Distribuidora / Mayorista'), ('pharmacy', 'Farmacia / Droguería'), ('other', 'Otro')], default='retail', help_text='Tipo de negocio — ajusta parámetros del modelo de forecast automáticamente', max_length=20),
        ),
    ]
