# Generated by Django 5.1.7 on 2026-04-04 05:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_tenant_business_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('price_change', 'Cambio de precio'), ('sale_void', 'Anulación de venta'), ('stock_adjust', 'Ajuste de stock'), ('product_create', 'Producto creado'), ('product_update', 'Producto actualizado'), ('product_delete', 'Producto desactivado'), ('purchase_post', 'Compra contabilizada'), ('purchase_void', 'Compra anulada'), ('transfer', 'Transferencia'), ('user_change', 'Cambio de usuario')], max_length=30)),
                ('entity_type', models.CharField(max_length=30)),
                ('entity_id', models.IntegerField()),
                ('detail', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='audit_entries', to='core.tenant')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'core_auditentry',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['tenant', '-created_at'], name='core_audite_tenant__79012c_idx'), models.Index(fields=['tenant', 'action'], name='core_audite_tenant__81869b_idx'), models.Index(fields=['tenant', 'entity_type', 'entity_id'], name='core_audite_tenant__bff5f1_idx')],
            },
        ),
    ]
