# Generated by Django 5.1.7 on 2026-04-04 18:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_add_audit_entry'),
    ]

    operations = [
        migrations.AddField(
            model_name='alertpreference',
            name='tenant',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='alert_preferences', to='core.tenant'),
        ),
    ]
