# Generated by Django 5.1.7 on 2026-04-05 19:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_alertpreference_add_tenant'),
        ('stores', '0003_store_default_warehouse'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserStoreAccess',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_access', to='stores.store')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='store_access_entries', to='core.tenant')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='store_access', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'core_userstoreaccess',
                'indexes': [models.Index(fields=['user', 'store'], name='core_userst_user_id_b3d6f2_idx'), models.Index(fields=['tenant', 'user'], name='core_userst_tenant__3ce4a2_idx')],
                'unique_together': {('user', 'store')},
            },
        ),
    ]
