# Generated by Django 5.1.7 on 2026-04-05 19:51

from django.db import migrations


def backfill_store_access(apps, schema_editor):
    """
    Grant existing users access to stores:
    - Owners: access to ALL stores in their tenant
    - Others: access to their current active_store only
    """
    User = apps.get_model("core", "User")
    Store = apps.get_model("stores", "Store")
    UserStoreAccess = apps.get_model("core", "UserStoreAccess")

    for user in User.objects.filter(tenant__isnull=False).select_related("tenant"):
        if user.role == "owner":
            # Owners get access to all stores
            stores = Store.objects.filter(tenant=user.tenant, is_active=True)
            for store in stores:
                UserStoreAccess.objects.get_or_create(
                    user=user, store=store,
                    defaults={"tenant": user.tenant},
                )
        elif user.active_store_id:
            # Non-owners get access to their active store
            UserStoreAccess.objects.get_or_create(
                user=user, store_id=user.active_store_id,
                defaults={"tenant": user.tenant},
            )


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_add_user_store_access'),
        ('stores', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(backfill_store_access, migrations.RunPython.noop),
    ]
