# Generated by Django 5.1.7 on 2026-04-20 22:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_backfill_user_store_access'),
    ]

    operations = [
        migrations.CreateModel(
            name='CronHeartbeat',
            fields=[
                ('task_name', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('last_run_at', models.DateTimeField(auto_now=True)),
                ('last_duration_s', models.FloatField(default=0)),
                ('last_result', models.CharField(default='ok', help_text='ok / failed / running', max_length=20)),
                ('last_error', models.CharField(blank=True, default='', max_length=500)),
                ('expected_max_age_minutes', models.IntegerField(default=90, help_text='Minutos máximos entre ejecuciones esperadas')),
            ],
            options={
                'db_table': 'core_cron_heartbeat',
            },
        ),
    ]
