# Generated by Django 5.1.7 on 2026-04-26 07:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_cronheartbeat'),
    ]

    operations = [
        migrations.AddField(
            model_name='tenant',
            name='internal_notes',
            field=models.TextField(blank=True, default='', help_text="Notas privadas del equipo Pulstock — visibles solo en superadmin (ej. 'Llamó por X, prefiere WhatsApp, dueño Pedro')"),
        ),
    ]
