# Generated by Django 5.1.15 on 2026-04-20 23:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_cronheartbeat'),
        ('core', '0017_merge_20260405_1600'),
    ]

    operations = [
    ]
