# Generated by Django 5.1.15 on 2026-04-26 07:48
#
# Merge migration que une las dos leaves que quedaron tras agregar el
# campo `internal_notes` a Tenant:
#   - 0018_merge_0017_cronheartbeat_0017_merge_20260405_1600 (huérfano,
#     recreado por pdeploy y por conftest.py en tests)
#   - 0018_tenant_internal_notes (mi nueva)
#
# Sin esta migración, `python manage.py migrate` falla con:
#   "Conflicting migrations detected; multiple leaf nodes in the
#   migration graph: (0018_merge_..., 0018_tenant_internal_notes)"
#
# Para tests locales: conftest.py recrea el huérfano antes de cargar
# las migrations (mismo patrón que pdeploy).

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_merge_0017_cronheartbeat_0017_merge_20260405_1600'),
        ('core', '0018_tenant_internal_notes'),
    ]

    operations = [
    ]
