# Generated by Django 5.1.15 on 2026-04-26 07:48
#
# Originalmente este archivo unía dos leaves de migración: el
# 0018_tenant_internal_notes con un 0018_merge huérfano que pdeploy
# recrea en cada deploy (ver docs/ops/04-deploy.md). Pero ese 0018_merge
# huérfano NO está en el repo — los tests locales / CI fallaban con
# NodeNotFoundError al intentar resolver el grafo.
#
# Como en producción esta migración YA está aplicada, las dependencies
# son solo metadata de orden (no operaciones). Cambiarlas en el repo no
# afecta el estado de la DB existente. Dejamos la dependency solo a
# 0018_tenant_internal_notes como única referencia válida en el repo.
#
# Si en el futuro hay un nuevo conflicto de leaves al agregar otra
# migración, generar otro merge y aplicar el mismo patrón.

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_tenant_internal_notes'),
    ]

    operations = [
    ]
