# Generated by Django 5.1.15 on 2026-04-26 07:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_merge_0017_cronheartbeat_0017_merge_20260405_1600'),
        ('core', '0018_tenant_internal_notes'),
    ]

    operations = [
    ]
