# Generated by Django 5.1.7 on 2026-05-22 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0019_merge_20260426_0348'),
    ]

    operations = [
        migrations.AddField(
            model_name='tenant',
            name='ingredient_forecast_trusted_from',
            field=models.DateField(blank=True, help_text='Fecha desde la que confiar en datos de Pulstock para forecast de ingredientes (datos previos = transicion).', null=True),
        ),
    ]
