# Generated by Django 5.1.7 on 2026-07-27 19:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0020_tenant_ingredient_forecast_trusted_from'),
    ]

    operations = [
        migrations.AddField(
            model_name='tenant',
            name='role_permissions_overrides',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
