# Generated by Django 5.1.7 on 2026-08-23 01:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0021_tenant_role_permissions_overrides'),
    ]

    operations = [
        migrations.AddField(
            model_name='alertpreference',
            name='reporte_abc',
            field=models.BooleanField(default=True),
        ),
    ]
