# Generated by Django 5.1.7 on 2026-03-26 03:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalog', '0010_backfill_product_unit_obj'),
        ('core', '0011_add_inventory_role'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Promotion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('discount_type', models.CharField(choices=[('pct', 'Porcentaje'), ('fixed_price', 'Precio fijo')], max_length=12)),
                ('discount_value', models.DecimalField(decimal_places=2, help_text='Porcentaje (ej: 30.00 para 30%) o precio fijo promocional', max_digits=12)),
                ('start_date', models.DateTimeField()),
                ('end_date', models.DateTimeField()),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='promotions', to='core.tenant')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PromotionProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('override_discount_value', models.DecimalField(blank=True, decimal_places=2, help_text='Override del valor de descuento para este producto específico', max_digits=12, null=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='promotion_items', to='catalog.product')),
                ('promotion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='promotions.promotion')),
            ],
        ),
        migrations.AddIndex(
            model_name='promotion',
            index=models.Index(fields=['tenant', 'is_active', 'start_date', 'end_date'], name='promotions__tenant__5d5a9a_idx'),
        ),
        migrations.AddIndex(
            model_name='promotionproduct',
            index=models.Index(fields=['product', 'promotion'], name='promotions__product_4113d2_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='promotionproduct',
            unique_together={('promotion', 'product')},
        ),
    ]
