# Generated by Django 5.1.7 on 2026-04-20 02:12

import django.db.models.deletion
import printing.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0016_backfill_user_store_access'),
        ('stores', '0003_store_default_warehouse'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PrintAgent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text="Nombre descriptivo, ej: 'PC de Caja Principal'", max_length=100)),
                ('api_key', models.CharField(db_index=True, default=printing.models._gen_api_key, help_text='API key que usa el agente para autenticarse', max_length=128, unique=True)),
                ('pairing_code', models.CharField(blank=True, db_index=True, default='', help_text='Código temporal que el usuario escribe en el agente', max_length=16)),
                ('pairing_code_expires_at', models.DateTimeField(blank=True, null=True)),
                ('paired_at', models.DateTimeField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('last_seen_at', models.DateTimeField(blank=True, help_text='Última vez que el agente hizo un poll', null=True)),
                ('version', models.CharField(blank=True, default='', help_text='Versión del software del agente', max_length=20)),
                ('os_info', models.CharField(blank=True, default='', help_text='OS reportado por el agente (Windows 10, etc.)', max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('store', models.ForeignKey(blank=True, help_text='Local al que pertenece este agente (opcional)', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='print_agents', to='stores.store')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='print_agents', to='core.tenant')),
            ],
            options={
                'db_table': 'printing_printagent',
            },
        ),
        migrations.CreateModel(
            name='AgentPrinter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Nombre de la impresora (como la reporta el OS)', max_length=150)),
                ('display_name', models.CharField(blank=True, default='', help_text='Nombre descriptivo para el usuario', max_length=150)),
                ('paper_width', models.IntegerField(choices=[(58, '58mm'), (80, '80mm')], default=80)),
                ('connection_type', models.CharField(choices=[('system', 'Sistema (impresora del OS)'), ('usb', 'USB directa'), ('network', 'Red (LAN por IP)')], default='system', max_length=20)),
                ('network_address', models.CharField(blank=True, default='', help_text="Solo para connection_type=network: '192.168.1.11:9100'", max_length=100)),
                ('is_default', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('agent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='printers', to='printing.printagent')),
            ],
            options={
                'db_table': 'printing_agentprinter',
            },
        ),
        migrations.CreateModel(
            name='PrintJob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('printer_name', models.CharField(blank=True, default='', help_text='Vacío = usar la impresora por defecto del agente', max_length=150)),
                ('data_b64', models.TextField(blank=True, default='', help_text='Base64 de bytes ESC/POS')),
                ('html', models.TextField(blank=True, default='', help_text='HTML para imprimir via diálogo del OS')),
                ('status', models.CharField(choices=[('pending', 'Pendiente'), ('printing', 'Imprimiendo'), ('done', 'Completado'), ('failed', 'Fallido'), ('cancelled', 'Cancelado')], db_index=True, default='pending', max_length=20)),
                ('error_msg', models.CharField(blank=True, default='', max_length=500)),
                ('retry_count', models.IntegerField(default=0)),
                ('source', models.CharField(blank=True, default='', help_text='Origen del trabajo: pos, mesa, manual, test', max_length=30)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('picked_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('agent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='jobs', to='printing.printagent')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='print_jobs', to='core.tenant')),
            ],
            options={
                'db_table': 'printing_printjob',
                'ordering': ['created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='printagent',
            index=models.Index(fields=['tenant', 'is_active'], name='printing_pr_tenant__2b9c92_idx'),
        ),
        migrations.AddIndex(
            model_name='printagent',
            index=models.Index(fields=['tenant', 'store'], name='printing_pr_tenant__1e7780_idx'),
        ),
        migrations.AddIndex(
            model_name='printagent',
            index=models.Index(fields=['pairing_code'], name='printing_pr_pairing_b49c3a_idx'),
        ),
        migrations.AddIndex(
            model_name='agentprinter',
            index=models.Index(fields=['agent', 'is_active'], name='printing_ag_agent_i_7f2ee2_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='agentprinter',
            unique_together={('agent', 'name')},
        ),
        migrations.AddIndex(
            model_name='printjob',
            index=models.Index(fields=['agent', 'status', 'created_at'], name='printing_pr_agent_i_492303_idx'),
        ),
        migrations.AddIndex(
            model_name='printjob',
            index=models.Index(fields=['tenant', 'status'], name='printing_pr_tenant__7f0180_idx'),
        ),
    ]
