# Generated by Django 5.1.7 on 2026-03-11 18:07

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_tenant_address_tenant_city_tenant_comuna_and_more'),
        ('sales', '0006_week2_protect_and_idempotency'),
        ('stores', '0003_store_default_warehouse'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='sale',
            index=models.Index(fields=['tenant', 'created_at'], name='sales_sale_tenant__165baa_idx'),
        ),
        migrations.AddIndex(
            model_name='sale',
            index=models.Index(fields=['tenant', 'status'], name='sales_sale_tenant__6a10bc_idx'),
        ),
    ]
