# Generated by Django 5.1.7 on 2026-03-11 18:52

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_tenant_address_tenant_city_tenant_comuna_and_more'),
        ('sales', '0007_week3_indexes'),
        ('stores', '0003_store_default_warehouse'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='sale',
            name='sale_number',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddConstraint(
            model_name='sale',
            constraint=models.UniqueConstraint(condition=models.Q(('sale_number', None), _negated=True), fields=('tenant', 'sale_number'), name='unique_sale_number_per_tenant'),
        ),
    ]
