# Generated by Django 5.1.7 on 2026-03-11 22:16

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0009_sale_payment'),
    ]

    operations = [
        migrations.AddField(
            model_name='sale',
            name='tip',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12),
        ),
    ]
