# Generated by Django 5.1.7 on 2026-03-11 22:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('caja', '0001_initial'),
        ('sales', '0010_tip_field'),
    ]

    operations = [
        migrations.AddField(
            model_name='sale',
            name='cash_session',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sales', to='caja.cashsession'),
        ),
    ]
