# Generated by Django 5.1.7 on 2026-03-12 00:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0011_add_cash_session'),
        ('tables', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sale',
            name='open_order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sales', to='tables.openorder'),
        ),
    ]
