# Generated by Django 5.1.7 on 2026-03-16 06:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0013_tenantsalecounter'),
    ]

    operations = [
        migrations.AlterField(
            model_name='salepayment',
            name='method',
            field=models.CharField(choices=[('cash', 'Efectivo'), ('card', 'Tarjeta Crédito'), ('debit', 'Tarjeta Débito'), ('transfer', 'Transferencia')], max_length=16),
        ),
    ]
