# Generated by Django 5.1.7 on 2026-03-20 03:30

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('caja', '0001_initial'),
        ('core', '0011_add_inventory_role'),
        ('sales', '0014_alter_salepayment_method'),
        ('stores', '0003_store_default_warehouse'),
        ('tables', '0004_add_is_cancelled_to_orderline'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='sale',
            name='sale_type',
            field=models.CharField(choices=[('VENTA', 'Venta'), ('CONSUMO_INTERNO', 'Consumo Interno')], db_index=True, default='VENTA', max_length=20),
        ),
        migrations.AddIndex(
            model_name='sale',
            index=models.Index(fields=['tenant', 'sale_type'], name='sales_sale_tenant__c5733f_idx'),
        ),
    ]
