# Generated by Django 5.1.7 on 2026-03-26 03:15

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('promotions', '0001_initial'),
        ('sales', '0015_sale_sale_type_sale_sales_sale_tenant__c5733f_idx'),
    ]

    operations = [
        migrations.AddField(
            model_name='saleline',
            name='discount_amount',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Descuento total aplicado en esta línea', max_digits=12),
        ),
        migrations.AddField(
            model_name='saleline',
            name='original_unit_price',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Precio original sin descuento', max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='saleline',
            name='promotion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sale_lines', to='promotions.promotion'),
        ),
    ]
