# Generated by Django 5.1.7 on 2026-04-15 02:45

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('caja', '0001_initial'),
        ('core', '0016_backfill_user_store_access'),
        ('sales', '0016_saleline_discount_amount_and_more'),
        ('stores', '0003_store_default_warehouse'),
        ('tables', '0006_add_floor_plan_fields'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='sale',
            name='unique_sale_idempotency_key_per_tenant',
        ),
        migrations.AddConstraint(
            model_name='sale',
            constraint=models.UniqueConstraint(condition=models.Q(('idempotency_key', ''), _negated=True), fields=('tenant', 'store', 'idempotency_key'), name='unique_sale_idempotency_key_per_store'),
        ),
    ]
