# Generated by Django 5.1.7 on 2026-04-29 21:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0017_remove_sale_unique_sale_idempotency_key_per_tenant_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sale',
            name='tip_method',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
    ]
