# Generated by Django 5.1.7 on 2026-04-29 22:05

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


def _backfill_tips(apps, schema_editor):
    """
    Convierte ventas legacy con `Sale.tip > 0` a filas de `SaleTip`.

    Reglas:
    - Si la venta tiene `tip_method` explícito → 1 SaleTip con esa propina y método.
    - Si `tip_method` está vacío → reparto proporcional según los SalePayments
      (la última fila absorbe el redondeo para que la suma cuadre exacto con
      `Sale.tip`). Si la venta no tiene payments, fallback a "cash".

    Idempotencia: sólo backfilea ventas que NO tengan filas SaleTip ya creadas.
    """
    from decimal import Decimal

    Sale = apps.get_model("sales", "Sale")
    SaleTip = apps.get_model("sales", "SaleTip")
    SalePayment = apps.get_model("sales", "SalePayment")

    sales_to_backfill = Sale.objects.filter(tip__gt=Decimal("0"))
    tips_to_create = []
    for sale in sales_to_backfill.iterator():
        # Skip si ya tiene SaleTips (idempotencia, p.ej. re-run de migración).
        if SaleTip.objects.filter(sale_id=sale.id).exists():
            continue

        explicit_method = (getattr(sale, "tip_method", "") or "").strip().lower()
        if explicit_method:
            tips_to_create.append(SaleTip(
                sale_id=sale.id,
                tenant_id=sale.tenant_id,
                method=explicit_method,
                amount=sale.tip,
            ))
            continue

        # Reparto proporcional según payments
        payments = list(SalePayment.objects.filter(sale_id=sale.id).order_by("id"))
        if not payments:
            tips_to_create.append(SaleTip(
                sale_id=sale.id,
                tenant_id=sale.tenant_id,
                method="cash",
                amount=sale.tip,
            ))
            continue

        total_paid = sum((p.amount for p in payments), Decimal("0"))
        if total_paid <= 0:
            # Edge case: payments con monto 0 → atribuir todo a cash
            tips_to_create.append(SaleTip(
                sale_id=sale.id,
                tenant_id=sale.tenant_id,
                method="cash",
                amount=sale.tip,
            ))
            continue

        running = Decimal("0")
        for p in payments[:-1]:
            share = (sale.tip * p.amount / total_paid).quantize(Decimal("0.01"))
            if share > 0:
                tips_to_create.append(SaleTip(
                    sale_id=sale.id,
                    tenant_id=sale.tenant_id,
                    method=p.method,
                    amount=share,
                ))
            running += share
        last = payments[-1]
        last_share = (sale.tip - running).quantize(Decimal("0.01"))
        if last_share > 0:
            tips_to_create.append(SaleTip(
                sale_id=sale.id,
                tenant_id=sale.tenant_id,
                method=last.method,
                amount=last_share,
            ))

    if tips_to_create:
        SaleTip.objects.bulk_create(tips_to_create, batch_size=500)


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0019_merge_20260426_0348'),
        ('sales', '0018_sale_tip_method'),
    ]

    operations = [
        migrations.CreateModel(
            name='SaleTip',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('method', models.CharField(choices=[('cash', 'Efectivo'), ('card', 'Tarjeta Crédito'), ('debit', 'Tarjeta Débito'), ('transfer', 'Transferencia')], max_length=16)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('sale', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tips', to='sales.sale')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.tenant')),
            ],
            options={
                'indexes': [models.Index(fields=['sale'], name='sales_salet_sale_id_63d68c_idx'), models.Index(fields=['tenant', 'method'], name='sales_salet_tenant__01a67e_idx')],
            },
        ),
        migrations.RunPython(
            code=_backfill_tips,
            reverse_code=migrations.RunPython.noop,
        ),
    ]
