# Generated by Django 5.1.7 on 2026-07-26 04:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


def backfill_waiter_from_open_order(apps, schema_editor):
    """Copia open_order.waiter → sale.waiter en las ventas de mesa existentes.

    Sale.waiter pasa a ser la fuente de verdad de reportes/propinas por garzón.
    Sin este backfill, las ventas históricas quedarían sin garzón hasta el
    próximo cobro. Solo toca ventas con open_order y garzón asignado.
    """
    from django.db.models import Subquery, OuterRef
    Sale = apps.get_model('sales', 'Sale')
    OpenOrder = apps.get_model('tables', 'OpenOrder')
    (
        Sale.objects
        .filter(open_order__isnull=False, open_order__waiter__isnull=False)
        .update(waiter=Subquery(
            OpenOrder.objects.filter(pk=OuterRef('open_order_id')).values('waiter_id')[:1]
        ))
    )


def noop_reverse(apps, schema_editor):
    """Reverso: dejar waiter en null (el schema revert elimina la columna)."""
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('caja', '0005_add_tip_withdraw_category'),
        ('core', '0020_tenant_ingredient_forecast_trusted_from'),
        ('sales', '0019_saletip_relational'),
        ('stores', '0003_store_default_warehouse'),
        ('tables', '0008_openorder_waiter'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='sale',
            name='waiter',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sales_as_waiter', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='sale',
            index=models.Index(fields=['tenant', 'waiter'], name='sales_sale_tenant__0a3909_idx'),
        ),
        migrations.RunPython(backfill_waiter_from_open_order, noop_reverse),
    ]
