# Generated by Django 5.1.7 on 2026-08-19 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0020_sale_waiter_sale_sales_sale_tenant__0a3909_idx'),
    ]

    operations = [
        migrations.AddField(
            model_name='sale',
            name='void_reason',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
    ]
